# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 02:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('company_name', models.CharField(db_column='Company name', max_length=200, primary_key=True, serialize=False)),
                ('status', models.TextField(db_column='Status')),
                ('category', models.TextField(db_column='Category')),
            ],
            options={
                'db_table': 'Account',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Contact name', max_length=120)),
                ('email', models.EmailField(db_column='Email', max_length=254)),
                ('phone', models.CharField(db_column='Phone', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}|(\\d{5}[\\-]\\d{6})$')])),
                ('notes', models.TextField()),
                ('account_company_name', models.ForeignKey(db_column='account_company_name', on_delete=django.db.models.deletion.CASCADE, to='crm_app.Account')),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='Date')),
                ('notes', models.TextField()),
                ('account_company_name', models.ForeignKey(db_column='account_company_name', on_delete=django.db.models.deletion.CASCADE, to='crm_app.Account')),
                ('contact_id', models.ForeignKey(db_column='contact_id', on_delete=django.db.models.deletion.CASCADE, to='crm_app.Contact')),
            ],
            options={
                'db_table': 'Meeting',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Project name', max_length=120)),
                ('notes', models.TextField()),
                ('status', models.TextField(db_column='Status')),
                ('account_company_name', models.ForeignKey(db_column='account_company_name', on_delete=django.db.models.deletion.CASCADE, to='crm_app.Account')),
            ],
            options={
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='crm_app.user')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='project_id',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='crm_app.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set([('email', 'phone')]),
        ),
    ]
