# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 02:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_auto_20170619_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(db_column='Email', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(db_column='Phone', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}|(\\d{5}[\\-]\\d{6})$')]),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='account_company_name',
            field=models.ForeignKey(db_column='account_companyname', on_delete=django.db.models.deletion.CASCADE, to='crm_app.Account'),
        ),
        migrations.AlterField(
            model_name='project',
            name='account_company_name',
            field=models.ForeignKey(db_column='account_companyname', on_delete=django.db.models.deletion.CASCADE, to='crm_app.Account'),
        ),
    ]
