# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_auto_20170619_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(db_column='Project name', max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('account_company_name', 'name')]),
        ),
    ]
