# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_auto_20170619_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateTimeField(db_column='Date'),
        ),
    ]
