# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0006_auto_20170620_0812'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meeting',
            unique_together=set([('date', 'account_company_name')]),
        ),
    ]
